//
//  KQHomePresenter.swift
//  TaskProjectDemo
//
//  Created by Muhammad Qasim Muhammad Mubeen on 28/01/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQHomePresentationLogic
{
  func displayonScreen(response: KQHome.Api.Response)
}

class KQHomePresenter: KQHomePresentationLogic
{
  weak var viewController: KQHomeDisplayLogic?
  
  // MARK: Display on Screen
  
  func displayonScreen(response: KQHome.Api.Response)
  {
      let viewModel = KQHome.Api.ViewModel(homeModel: response.homeModel?.results)
      viewController?.displayHomeList(viewModel: viewModel)
  }
}
