//
//  KQHomeRouter.swift
//  TaskProjectDemo
//
//  Created by Muhammad Qasim Muhammad Mubeen on 28/01/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol KQHomeRoutingLogic
{
    func routeToItemDetails(segue: UIStoryboardSegue?)
}

protocol KQHomeDataPassing
{
    var dataStore: KQHomeDataStore? { get set }
}

class KQHomeRouter: NSObject, KQHomeRoutingLogic, KQHomeDataPassing
{
    weak var viewController: KQHomeViewController?
    var dataStore: KQHomeDataStore?
    
    // MARK: Routing
    func routeToItemDetails(segue: UIStoryboardSegue?) {
        guard let destinationVC = AppLocalNetworkRoutes.getItemDetialsView() as? KQItemDetailsViewController else{return}
        guard let destinationRouter = destinationVC.router else {return}
        guard var destinationDS = destinationRouter.dataStore else {return}
        guard let sourceDS = dataStore else {return}
        passDataToSomewhere(source: sourceDS , destination: &destinationDS)
        navigateToItemDetails(source: viewController!, destination: destinationVC)
    }
    // MARK: Navigation
    func navigateToItemDetails(source: KQHomeViewController, destination: KQItemDetailsViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: KQHomeDataStore, destination: inout KQItemDetailsDataStore)
    {
        destination.post = source.selectedPost
    }
}
