//
//  KQHomeWorker.swift
//  TaskProjectDemo
//
//  Created by Muhammad Qasim Muhammad Mubeen on 28/01/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class KQHomeWorker
{
    // RequestValidation
  func homeApiRequest(completion:@escaping((_ message:HomeModel?,_ error:Error?) -> ()))
  {            
  }
}
