//
//  KQLoginWorker.swift
//  TaskProjectDemo
//
//  Created by Apple on 10/30/19.
//  Copyright (c) 2019 Apple. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class KQLoginWorker
{
    func validateInputs(request : KQLogin.Api.Request) -> (isValidate: Bool, message: String) {
        
        
        if let empty = checkEmpty(email: request.email, password: request.password){
            if empty != "" {
                return (false,"Email or password can not be empty")
            }else{
                return (true,"")
            }
        }
        
        if !self.isValidEmail(email: request.email){
            return (false,"Invalid email")
        }
        
        if !self.isValidPassword(testStr: request.password) {
            return (false,"The password must be at least 6 characters long")
        }
        
        return (true,"")
    }
    
    func checkEmpty(email: String?, password: String?) -> String?
    {
        
        if let email = email, let password = password {
            return "\(email) \(password)."
        }
        
        if let email = email {
            return "\(email)."
        }
        
        if let password = password {
            return "\(password)."
        }
        
        return nil
    }
    
    func isValidName(in text: String) -> Bool
    {
        do
        {
            let regex = try NSRegularExpression(pattern: "^[0-9a-zA-Z\\_]{7,18}$", options: .caseInsensitive)
            if regex.matches(in: text, options: [], range: NSMakeRange(0, text.count)).count > 0 {return true}
        }
        catch {}
        return false
    }
    
    func isValidEmail(email:String) -> Bool {
        let emailRegEx = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}"
        let emailTest = NSPredicate(format:"SELF MATCHES %@", emailRegEx)
        return emailTest.evaluate(with: email)
    }
    
    func isValidPassword(testStr: String) -> Bool {
        if testStr.count >= 6 {
            return true
        }
        return false
    }
}
