//
//  LoginVCModels.swift
//  TaskProjectDemo
//
//  Created by Apple on 10/15/19.
//  Copyright (c) 2019 Apple. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum KQLogin
{
  // MARK: Use cases

  enum Something
  {
    struct Request
    {
        var email : String
        var password: String
    }

    struct Response
    {
        var success : Bool
        var message : String
        var userLogin:LoginModel
    }

    struct ViewModel
    {
        var user: User
    }
  }
}
