//
//  KQItemDetailsInteractor.swift
//  TaskProjectDemo
//
//  Created by Muhammad Qasim Muhammad Mubeen on 30/01/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQItemDetailsBusinessLogic
{
    func ItemDetailsData(request: KQItemDetails.Screen.Request)
}

protocol KQItemDetailsDataStore
{
    var post: Post? { get set }
}

class KQItemDetailsInteractor: KQItemDetailsBusinessLogic, KQItemDetailsDataStore
{
    
    var post: Post?
    var presenter: KQItemDetailsPresentationLogic?
    var worker: KQItemDetailsWorker?
    
    // MARK: Item Details Data
    
    func ItemDetailsData(request: KQItemDetails.Screen.Request)
    {
        worker = KQItemDetailsWorker()
        worker?.doSomeWork()
        if let post = post {
            let response = KQItemDetails.Screen.Response(post: post)
            presenter?.displayOnScreen(response: response)
        }
    }
}
